const GET_CUSTERLIST="GET_CUSTERLIST"
const GET_CASE="GET_CASE"
const POST_LOGIN="POST_LOGIN"
const OUT_LOGIN='OUT_LOGIN'
const MENU_ITEM='MENU_ITEM'
export{GET_CUSTERLIST,GET_CASE,POST_LOGIN,OUT_LOGIN,MENU_ITEM}